//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalConverterProjectInstaller.languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniversalConverterProjectInstaller.languages.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup.
        /// </summary>
        public static string BUTTON_CLEANUP {
            get {
                return ResourceManager.GetString("BUTTON_CLEANUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string BUTTON_CLOSE {
            get {
                return ResourceManager.GetString("BUTTON_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string BUTTON_FORWARD {
            get {
                return ResourceManager.GetString("BUTTON_FORWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string BUTTON_NEXT {
            get {
                return ResourceManager.GetString("BUTTON_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string BUTTON_OK {
            get {
                return ResourceManager.GetString("BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string BUTTON_UPDATE {
            get {
                return ResourceManager.GetString("BUTTON_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string BUTTON_X {
            get {
                return ResourceManager.GetString("BUTTON_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This installer will install FIFA Manager {0} Patch to your FIFA Manager..
        /// </summary>
        public static string DESCRIPTION_TEXT {
            get {
                return ResourceManager.GetString("DESCRIPTION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This installer will install FIFA Manager {0} Patch (Update {1}) to your FIFA Manager..
        /// </summary>
        public static string DESCRIPTION_TEXT_UPDATE {
            get {
                return ResourceManager.GetString("DESCRIPTION_TEXT_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are errors in config file format.
        /// </summary>
        public static string ERROR_CONFIG {
            get {
                return ResourceManager.GetString("ERROR_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing file:.
        /// </summary>
        public static string ERROR_MISSING_FILE {
            get {
                return ResourceManager.GetString("ERROR_MISSING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing files:.
        /// </summary>
        public static string ERROR_MISSING_FILES {
            get {
                return ResourceManager.GetString("ERROR_MISSING_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to abort the installation? All applied changes won&apos;t be reverted..
        /// </summary>
        public static string INSTALL_ABORT {
            get {
                return ResourceManager.GetString("INSTALL_ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the green &quot;OK&quot; button to close the installer..
        /// </summary>
        public static string INSTALL_CLOSE {
            get {
                return ResourceManager.GetString("INSTALL_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string INSTALL_ERROR {
            get {
                return ResourceManager.GetString("INSTALL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error during the installation. Press the grey &quot;X&quot; button to close the installer..
        /// </summary>
        public static string INSTALL_ERROR_CLOSE {
            get {
                return ResourceManager.GetString("INSTALL_ERROR_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation completed..
        /// </summary>
        public static string INSTALL_FINISHED {
            get {
                return ResourceManager.GetString("INSTALL_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no enough space for installation. Please, clean the space and press the &quot;Refresh&quot; button. If you want to change the destination folder, please close the installer and run it again. To force the installation, press the red &quot;Forward&quot; button..
        /// </summary>
        public static string INSTALL_NO_SPACE {
            get {
                return ResourceManager.GetString("INSTALL_NO_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation is started. Installation progress:.
        /// </summary>
        public static string INSTALL_PROGRESS {
            get {
                return ResourceManager.GetString("INSTALL_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose installation type:.
        /// </summary>
        public static string INSTALLDIR_ACTION {
            get {
                return ResourceManager.GetString("INSTALLDIR_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string INSTALLDIR_BROWSE {
            get {
                return ResourceManager.GetString("INSTALLDIR_BROWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t install patch updates because the installed patch configuration does not match with available installer files. You still have option to reinstall the patch with new configuration..
        /// </summary>
        public static string INSTALLDIR_CONFIG_DOES_NOT_MATCH {
            get {
                return ResourceManager.GetString("INSTALLDIR_CONFIG_DOES_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to install updates for current patch configuration, make sure these files are available:.
        /// </summary>
        public static string INSTALLDIR_CONFIG_MAKE_SURE {
            get {
                return ResourceManager.GetString("INSTALLDIR_CONFIG_MAKE_SURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Not a FIFA Manager directory. Please check carefully: there must be &quot;GfxCore.dll&quot; file and &quot;fmdata&quot; folder, among with other files and folders, in FIFA Manager directory..
        /// </summary>
        public static string INSTALLDIR_ERROR {
            get {
                return ResourceManager.GetString("INSTALLDIR_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose FIFA Manager folder:.
        /// </summary>
        public static string INSTALLDIR_HEADER {
            get {
                return ResourceManager.GetString("INSTALLDIR_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install patch.
        /// </summary>
        public static string INSTALLDIR_INSTALL {
            get {
                return ResourceManager.GetString("INSTALLDIR_INSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Update {0}.
        /// </summary>
        public static string INSTALLDIR_INSTALL_UPDATE {
            get {
                return ResourceManager.GetString("INSTALLDIR_INSTALL_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Updates {0} and {1}.
        /// </summary>
        public static string INSTALLDIR_INSTALL_UPDATES {
            get {
                return ResourceManager.GetString("INSTALLDIR_INSTALL_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install patch with all updates.
        /// </summary>
        public static string INSTALLDIR_INSTALL_WITH_UPDATES {
            get {
                return ResourceManager.GetString("INSTALLDIR_INSTALL_WITH_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t install the patch because these files are missing:.
        /// </summary>
        public static string INSTALLDIR_MISSING_FILES {
            get {
                return ResourceManager.GetString("INSTALLDIR_MISSING_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t reinstall the patch with this installer because these files are missing:.
        /// </summary>
        public static string INSTALLDIR_MISSING_FILES_REINSTALL {
            get {
                return ResourceManager.GetString("INSTALLDIR_MISSING_FILES_REINSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But you can&apos;t reinstall the patch because these files are missing:.
        /// </summary>
        public static string INSTALLDIR_MISSING_FILES_REINSTALL_BUT {
            get {
                return ResourceManager.GetString("INSTALLDIR_MISSING_FILES_REINSTALL_BUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t install patch updates because these files are missing:.
        /// </summary>
        public static string INSTALLDIR_MISSING_FILES_UPDATES {
            get {
                return ResourceManager.GetString("INSTALLDIR_MISSING_FILES_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: It&apos;s recommended to install this patch on a fresh clean game. The installer may remove (delete) some files and folders inside selected installation folder..
        /// </summary>
        public static string INSTALLDIR_NOTE {
            get {
                return ResourceManager.GetString("INSTALLDIR_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is ready for the install..
        /// </summary>
        public static string INSTALLDIR_READY {
            get {
                return ResourceManager.GetString("INSTALLDIR_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall patch.
        /// </summary>
        public static string INSTALLDIR_REINSTALL {
            get {
                return ResourceManager.GetString("INSTALLDIR_REINSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall Update {0}.
        /// </summary>
        public static string INSTALLDIR_REINSTALL_UPDATE {
            get {
                return ResourceManager.GetString("INSTALLDIR_REINSTALL_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall Updates {0} and {1}.
        /// </summary>
        public static string INSTALLDIR_REINSTALL_UPDATES {
            get {
                return ResourceManager.GetString("INSTALLDIR_REINSTALL_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall patch with all updates.
        /// </summary>
        public static string INSTALLDIR_REINSTALL_WITH_UPDATES {
            get {
                return ResourceManager.GetString("INSTALLDIR_REINSTALL_WITH_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the green &quot;OK&quot; button to start the installation..
        /// </summary>
        public static string INSTALLDIR_START {
            get {
                return ResourceManager.GetString("INSTALLDIR_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You still have option to reinstall the patch..
        /// </summary>
        public static string INSTALLDIR_STILL_REINSTALL {
            get {
                return ResourceManager.GetString("INSTALLDIR_STILL_REINSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You still have option to reinstall Update {0}..
        /// </summary>
        public static string INSTALLDIR_STILL_REINSTALL_UPDATE {
            get {
                return ResourceManager.GetString("INSTALLDIR_STILL_REINSTALL_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You still have option to reinstall Updates {0} and {1}..
        /// </summary>
        public static string INSTALLDIR_STILL_REINSTALL_UPDATES {
            get {
                return ResourceManager.GetString("INSTALLDIR_STILL_REINSTALL_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0}.
        /// </summary>
        public static string INSTALLDIR_UPDATE {
            get {
                return ResourceManager.GetString("INSTALLDIR_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently installed version is FIFA Manager {0}.{1}..
        /// </summary>
        public static string INSTALLDIR_VERSION_CURRENT {
            get {
                return ResourceManager.GetString("INSTALLDIR_VERSION_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently installed version ({0}.{1}) is greater than installer version ({0}.{2}). It could be that you are using an outdated installer version. With this installer, you can only update the patch version to {0}.{2} by reinstalling the patch..
        /// </summary>
        public static string INSTALLDIR_VERSION_GREATER {
            get {
                return ResourceManager.GetString("INSTALLDIR_VERSION_GREATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patch (FIFA Manager {0}) was not yet installed on this game..
        /// </summary>
        public static string INSTALLDIR_VERSION_NOT_INSTALLED {
            get {
                return ResourceManager.GetString("INSTALLDIR_VERSION_NOT_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already installed patch version {0}.{1} (the same with installer version)..
        /// </summary>
        public static string INSTALLDIR_VERSION_SAME {
            get {
                return ResourceManager.GetString("INSTALLDIR_VERSION_SAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Banners pack.
        /// </summary>
        public static string INSTALLOPTION_3D_BANNERPACK {
            get {
                return ResourceManager.GetString("INSTALLOPTION_3D_BANNERPACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Faces pack.
        /// </summary>
        public static string INSTALLOPTION_3D_FACEPACK {
            get {
                return ResourceManager.GetString("INSTALLOPTION_3D_FACEPACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Kits pack.
        /// </summary>
        public static string INSTALLOPTION_3D_KITPACK {
            get {
                return ResourceManager.GetString("INSTALLOPTION_3D_KITPACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Stadiums pack.
        /// </summary>
        public static string INSTALLOPTION_3D_STADPACK {
            get {
                return ResourceManager.GetString("INSTALLOPTION_3D_STADPACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available space:.
        /// </summary>
        public static string INSTALLOPTION_AVAILABLE_SPACE {
            get {
                return ResourceManager.GetString("INSTALLOPTION_AVAILABLE_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select badges style.
        /// </summary>
        public static string INSTALLOPTION_BADGES {
            get {
                return ResourceManager.GetString("INSTALLOPTION_BADGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Style.
        /// </summary>
        public static string INSTALLOPTION_BADGES_1 {
            get {
                return ResourceManager.GetString("INSTALLOPTION_BADGES_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} badges.
        /// </summary>
        public static string INSTALLOPTION_BADGES_1_INFO1 {
            get {
                return ResourceManager.GetString("INSTALLOPTION_BADGES_1_INFO1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fm-zocker.de production.
        /// </summary>
        public static string INSTALLOPTION_BADGES_1_INFO2 {
            get {
                return ResourceManager.GetString("INSTALLOPTION_BADGES_1_INFO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shine and Outline Style.
        /// </summary>
        public static string INSTALLOPTION_BADGES_2 {
            get {
                return ResourceManager.GetString("INSTALLOPTION_BADGES_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} badges.
        /// </summary>
        public static string INSTALLOPTION_BADGES_2_INFO1 {
            get {
                return ResourceManager.GetString("INSTALLOPTION_BADGES_2_INFO1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fm-zocker.de production.
        /// </summary>
        public static string INSTALLOPTION_BADGES_2_INFO2 {
            get {
                return ResourceManager.GetString("INSTALLOPTION_BADGES_2_INFO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges style.
        /// </summary>
        public static string INSTALLOPTION_BADGES_CB {
            get {
                return ResourceManager.GetString("INSTALLOPTION_BADGES_CB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unneded files in game and Documents folder before the installation.
        /// </summary>
        public static string INSTALLOPTION_CLEANUP_TIP {
            get {
                return ResourceManager.GetString("INSTALLOPTION_CLEANUP_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final configuration.
        /// </summary>
        public static string INSTALLOPTION_FINAL {
            get {
                return ResourceManager.GetString("INSTALLOPTION_FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Language.
        /// </summary>
        public static string INSTALLOPTION_GAMELANGUAGE {
            get {
                return ResourceManager.GetString("INSTALLOPTION_GAMELANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change the language later, with &quot;Language Selector&quot; tool (available in game folder).
        /// </summary>
        public static string INSTALLOPTION_GAMELANGUAGE_TIP {
            get {
                return ResourceManager.GetString("INSTALLOPTION_GAMELANGUAGE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select portraits style.
        /// </summary>
        public static string INSTALLOPTION_PORTRAITS {
            get {
                return ResourceManager.GetString("INSTALLOPTION_PORTRAITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football Manager Style.
        /// </summary>
        public static string INSTALLOPTION_PORTRAITS_1 {
            get {
                return ResourceManager.GetString("INSTALLOPTION_PORTRAITS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} portraits.
        /// </summary>
        public static string INSTALLOPTION_PORTRAITS_1_INFO1 {
            get {
                return ResourceManager.GetString("INSTALLOPTION_PORTRAITS_1_INFO1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sortitoutsi.net production.
        /// </summary>
        public static string INSTALLOPTION_PORTRAITS_1_INFO2 {
            get {
                return ResourceManager.GetString("INSTALLOPTION_PORTRAITS_1_INFO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFA Manager Style.
        /// </summary>
        public static string INSTALLOPTION_PORTRAITS_2 {
            get {
                return ResourceManager.GetString("INSTALLOPTION_PORTRAITS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} portraits.
        /// </summary>
        public static string INSTALLOPTION_PORTRAITS_2_INFO1 {
            get {
                return ResourceManager.GetString("INSTALLOPTION_PORTRAITS_2_INFO1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fm-zocker.de production.
        /// </summary>
        public static string INSTALLOPTION_PORTRAITS_2_INFO2 {
            get {
                return ResourceManager.GetString("INSTALLOPTION_PORTRAITS_2_INFO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portraits style.
        /// </summary>
        public static string INSTALLOPTION_PORTRAITS_CB {
            get {
                return ResourceManager.GetString("INSTALLOPTION_PORTRAITS_CB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate available space.
        /// </summary>
        public static string INSTALLOPTION_REFRESH_TIP {
            get {
                return ResourceManager.GetString("INSTALLOPTION_REFRESH_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Graphics from Documents folder.
        /// </summary>
        public static string INSTALLOPTION_REMOVE_GRAPHICS {
            get {
                return ResourceManager.GetString("INSTALLOPTION_REMOVE_GRAPHICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove SaveGames from Documents folder.
        /// </summary>
        public static string INSTALLOPTION_REMOVE_SAVEGAMES {
            get {
                return ResourceManager.GetString("INSTALLOPTION_REMOVE_SAVEGAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required space for installation:.
        /// </summary>
        public static string INSTALLOPTION_REQUIRED_SPACE {
            get {
                return ResourceManager.GetString("INSTALLOPTION_REQUIRED_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select style.
        /// </summary>
        public static string INSTALLOPTION_SELECT {
            get {
                return ResourceManager.GetString("INSTALLOPTION_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select theme.
        /// </summary>
        public static string INSTALLOPTION_SELECT_THEME {
            get {
                return ResourceManager.GetString("INSTALLOPTION_SELECT_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stadiums.
        /// </summary>
        public static string INSTALLOPTION_STADIUMS_1 {
            get {
                return ResourceManager.GetString("INSTALLOPTION_STADIUMS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic ({0} stadiums).
        /// </summary>
        public static string INSTALLOPTION_STADIUMS_2 {
            get {
                return ResourceManager.GetString("INSTALLOPTION_STADIUMS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full ({0} stadiums).
        /// </summary>
        public static string INSTALLOPTION_STADIUMS_3 {
            get {
                return ResourceManager.GetString("INSTALLOPTION_STADIUMS_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select theme.
        /// </summary>
        public static string INSTALLOPTION_THEME {
            get {
                return ResourceManager.GetString("INSTALLOPTION_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        public static string INSTALLOPTION_THEME_1 {
            get {
                return ResourceManager.GetString("INSTALLOPTION_THEME_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string INSTALLOPTION_THEME_2 {
            get {
                return ResourceManager.GetString("INSTALLOPTION_THEME_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string INSTALLOPTION_THEME_3 {
            get {
                return ResourceManager.GetString("INSTALLOPTION_THEME_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string INSTALLOPTION_THEME_CB {
            get {
                return ResourceManager.GetString("INSTALLOPTION_THEME_CB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change the theme in Game options when you want.
        /// </summary>
        public static string INSTALLOPTION_THEME_NOTE {
            get {
                return ResourceManager.GetString("INSTALLOPTION_THEME_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XXL Portraits.
        /// </summary>
        public static string INSTALLOPTION_XXL_PORTRAITS {
            get {
                return ResourceManager.GetString("INSTALLOPTION_XXL_PORTRAITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the license agreement.
        /// </summary>
        public static string LICENSE_ACCEPT {
            get {
                return ResourceManager.GetString("LICENSE_ACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read the license agreement..
        /// </summary>
        public static string LICENSE_HEADER {
            get {
                return ResourceManager.GetString("LICENSE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a modification (patch) for a FIFA Manager game (created by EA Sports).
        ///
        ///This patch was created solely on enthusiasm from a team of FIFA Manager series fans, and does not involve any commercial use.
        ///
        ///The distribution of this patch on any other web resources is possible only with the use of original patch files (including this installer) and only under the original patch name.
        ///
        ///THIS SOFTWARE/MODIFICATION IS PROVIDED &quot;AS IS&quot;, WITHOUT WARRANTY OF ANY KIND..
        /// </summary>
        public static string LICENSE_TEXT {
            get {
                return ResourceManager.GetString("LICENSE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the green &quot;Forward&quot; button to go to installation options..
        /// </summary>
        public static string NEXT_INSTALLOPTIONS {
            get {
                return ResourceManager.GetString("NEXT_INSTALLOPTIONS", resourceCulture);
            }
        }
    }
}
